// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_exceptions from "../node_modules/rescript/lib/es6/caml_exceptions.js";

var p = new Promise((function (resolve, _reject) {
        console.log("Inside a promise");
        resolve("chain me!");
      }));

p.then(function (msg) {
      console.log(msg);
      return Promise.resolve(undefined);
    });

var PromiseFoo = /* @__PURE__ */Caml_exceptions.create("PromiseSimple.PromiseFoo");

p.then(function (msg) {
      return Promise.reject({
                  RE_EXN_ID: PromiseFoo,
                  _1: msg
                });
    });

function PromiseSimple(Props) {
  return React.createElement("div", {
              className: "font-semibold dark:text-white"
            }, "Promise");
}

var make = PromiseSimple;

export {
  p ,
  PromiseFoo ,
  make ,
}
/* p Not a pure module */
